export const SITE = {
  name: 'S2H',
  slogan: 'From Screen to Reality',
  sloganAr: 'من الشاشة للحقيقة',
  phone: '01038572827',
  whatsapp: '201038572827',
  email: 's2h.figures@gmail.com',
  instagram: 's2h.figures',
  tiktok: 's2h1970',
  facebook: 'S2H Figures',
  location: 'Cairo, Egypt',
  locationAr: 'القاهرة، مصر',
  domain: 's2h.online',
  established: '2025',
}

export const PRODUCTS = [
  {
    id: 'gojo',
    name: 'Gojo Satoru',
    nameAr: 'جوجو ساتورو',
    series: 'Jujutsu Kaisen',
    seriesAr: 'جوجوتسو كايزن',
    price: 500,
    size: '12cm',
    tag: 'Most Popular',
    tagAr: 'الأكثر مبيعاً',
    emoji: '🩵',
    hot: true,
  },
  {
    id: 'goku',
    name: 'Goku',
    nameAr: 'جوكو',
    series: 'Dragon Ball Z',
    seriesAr: 'دراغون بول زد',
    price: 500,
    size: '12cm',
    tag: 'Best Seller',
    tagAr: 'الأكثر مبيعاً',
    emoji: '⚡',
    hot: true,
  },
  {
    id: 'spiderman',
    name: 'Spider-Man',
    nameAr: 'سبايدر مان',
    series: 'Marvel',
    seriesAr: 'مارفيل',
    price: 500,
    size: '12cm',
    tag: 'Fan Favourite',
    tagAr: 'المفضل',
    emoji: '🕷️',
    hot: true,
  },
  {
    id: 'duck',
    name: 'Strong Duck',
    nameAr: 'البطة الجامدة',
    series: 'Viral Edition',
    seriesAr: 'النسخة الفيروسية',
    price: 500,
    size: '12cm',
    tag: 'Trending',
    tagAr: 'ترند',
    emoji: '🦆',
    hot: true,
  },
  {
    id: 'batman',
    name: 'Batman',
    nameAr: 'باتمان',
    series: 'DC Comics',
    seriesAr: 'دي سي كوميكس',
    price: 500,
    size: '12cm',
    tag: 'Classic',
    tagAr: 'كلاسيك',
    emoji: '🦇',
    hot: false,
  },
  {
    id: 'messi',
    name: 'Lionel Messi',
    nameAr: 'ليونيل ميسي',
    series: 'Football Icons',
    seriesAr: 'أساطير الكرة',
    price: 500,
    size: '12cm',
    tag: 'GOAT',
    tagAr: 'الأعظم',
    emoji: '🐐',
    hot: false,
  },
  {
    id: 'ronaldo',
    name: 'Cristiano Ronaldo',
    nameAr: 'كريستيانو رونالدو',
    series: 'Football Icons',
    seriesAr: 'أساطير الكرة',
    price: 500,
    size: '12cm',
    tag: 'Legend',
    tagAr: 'أسطورة',
    emoji: '⚽',
    hot: false,
  },
  {
    id: 'mbappe',
    name: 'Kylian Mbappé',
    nameAr: 'كيليان مبابي',
    series: 'Football Icons',
    seriesAr: 'أساطير الكرة',
    price: 500,
    size: '12cm',
    tag: 'New',
    tagAr: 'جديد',
    emoji: '🚀',
    hot: false,
  },
  {
    id: 'yamal',
    name: 'Lamine Yamal',
    nameAr: 'لامين يامال',
    series: 'Football Icons',
    seriesAr: 'أساطير الكرة',
    price: 500,
    size: '12cm',
    tag: 'Rising Star',
    tagAr: 'نجم صاعد',
    emoji: '🌟',
    hot: false,
  },
  {
    id: 'black-duck',
    name: 'Strong Black Duck',
    nameAr: 'البطة السوداء الجامدة',
    series: 'Viral Edition',
    seriesAr: 'النسخة الفيروسية',
    price: 500,
    size: '12cm',
    tag: 'Trending',
    tagAr: 'ترند',
    emoji: '🖤',
    hot: false,
  },
]

export const HOT_PRODUCTS = PRODUCTS.filter(p => p.hot)

export const STEPS = [
  {
    num: '01',
    en: 'Pick your figure',
    ar: 'اختار فيجورك',
    descEn: 'Browse our collection and pick the one you want.',
    descAr: 'اتفرج على الكولكشن واختار اللي يعجبك.',
  },
  {
    num: '02',
    en: 'Order on WhatsApp',
    ar: 'اطلب على واتساب',
    descEn: 'One click opens WhatsApp with your order ready to send.',
    descAr: 'ضغطة واحدة وهيفتح واتساب وطلبك جاهز.',
  },
  {
    num: '03',
    en: 'We deliver to your door',
    ar: 'بنوصلك على الباب',
    descEn: 'Cash on delivery, anywhere in Egypt. Fast and safe.',
    descAr: 'الدفع عند الاستلام، في أي مكان في مصر. سريع وأمان.',
  },
]

export const WHY_US = [
  {
    icon: '🎨',
    en: 'High Detail Prints',
    ar: 'طباعة عالية التفاصيل',
    descEn: 'Every figure is printed with precision at 0.1mm layer accuracy.',
    descAr: 'كل فيجور بيتطبع بدقة 0.1 مم.',
  },
  {
    icon: '📦',
    en: 'Delivered Everywhere',
    ar: 'بنوصل لكل مصر',
    descEn: 'We ship to every city in Egypt. Fast and safe packaging.',
    descAr: 'بنشحن لكل محافظات مصر. تغليف أمين وسريع.',
  },
  {
    icon: '💸',
    en: 'Cash on Delivery',
    ar: 'الدفع عند الاستلام',
    descEn: 'No online payments needed. Pay when you receive your order.',
    descAr: 'مش محتاج تدفع أونلاين. ادفع لما يوصلك الطلب.',
  },
  {
    icon: '💬',
    en: 'Direct Support',
    ar: 'تواصل مباشر',
    descEn: 'Talk to us directly on WhatsApp. Real humans, no bots.',
    descAr: 'كلمنا على واتساب مباشرة. بشر حقيقيين مش بوتات.',
  },
]
